Add nobarrier and lazytime boot options
sn99/Optimizing-linux pull request #12
Opened 2024-03-02 11:19 UTC by kawaii-ghost

> `nobarrier`

On  a  device  with a volatile battery-backed write-back cache, the nobarrier option will not lead  to  filesystem  corruption  as  the pending blocks are supposed to make it to the permanent storage.

So as long powerloss didn't happen it's totally fine :).

> `lazytime`

This mount option significantly reduces writes to the inode table for workloads that perform frequent random writes to preallocated files.

2024-03-03 19:17 UTC, sn99 commented
Hi, thanks for the PR, I will have a better look soon, on surface level 'nobarrier' looks a bit risky but again nothing that can be incorporated in the guide after all.

2024-03-04 10:40 UTC, sn99 commented
@kawaii-ghost can you add a collapsable warning section indicating what these 2 options do.

2024-03-05 07:25 UTC, sn99 requested changes

2024-03-05 07:25 UTC, sn99 commented on README.md
@kawaii-ghost can you add a collapsable warning section indicating what these 2 options do.

2024-03-09 20:27 UTC, merged

2024-03-12 04:44 UTC, kawaii-ghost commented
Sorry, I just noticed that I double typed description about `nobarrier`. Should I submit new PR?